### ISSUE TITLE
Сами пометки перевести? 

### ISSUE THREAD

**Issue by sutyrin** [KotRikD/conventionalcomments-ru#1]
Привет, спасибо за инициативу перевода! Отличная, нужная вещь) 

Я вот думаю внедрять в проекте, и задаюсь вопросом — не нужно ли разработать перевод самих меток, если в проекте принято все комментарии вообще по-русски писать? 

типа: 

`issue:` — `проблема:`
`thought:` — `идея:`
`todo:` — `дело:`
`chore:` — `надо:`
`note:` — `примечание:`
`praise:` — `каеф:` / `браво!:`
`suggestion:` — `предложение:`

**Comment by KotRikD** [comment]
Я думаю это от проекта к проекту :) Всё же суть перевода была донести, что есть такой клёвый подход и есть какой-то базовый набор этих меток.

"Не стесняйтесь отклоняться от этого списка меток, если это кажется уместным."

**Comment by sutyrin** [comment]
Согласен. Благодарю)
